name: Release
on:
  workflow_run:
    workflows: ["Test", "Versioning"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    name: Publish Package
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3

      - run: yarn
      - run: yarn version apply
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[ci skip] apply version"
          commit_options: '--no-verify --signoff'
          file_pattern: 'package.json .yarn/versions/*'

      - run: yarn build
      - run: yarn npm publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

