name: Versioning
on: [push]

jobs:
  build:
    name: Version Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Also check out main branch, so yarn can compare
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: yarn
      - run: yarn version check
